
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartlite.h"

/*
* The configuration table for devices
*/

XUartLite_Config XUartLite_ConfigTable[] =
{
	{
		XPAR_MDM_1_DEVICE_ID,
		XPAR_MDM_1_BASEADDR,
		XPAR_MDM_1_BAUDRATE,
		XPAR_MDM_1_USE_PARITY,
		XPAR_MDM_1_ODD_PARITY,
		XPAR_MDM_1_DATA_BITS
	}
};


