
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xsysmon.h"

/*
* The configuration table for devices
*/

XSysMon_Config XSysMon_ConfigTable[] =
{
	{
		XPAR_XADC_WIZ_0_DEVICE_ID,
		XPAR_XADC_WIZ_0_BASEADDR,
		XPAR_XADC_WIZ_0_INCLUDE_INTR
	}
};


