# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/kc705_pcie/kc705_pcie.srcs/sources_1/ip/kc705_pcie_x8_gen2/kc705_pcie_x8_gen2.xci
# IP: The module: 'kc705_pcie_x8_gen2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/kc705_pcie/kc705_pcie.srcs/sources_1/ip/kc705_pcie_x8_gen2/source/kc705_pcie_x8_gen2-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_pcie_x8_gen2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/kc705_pcie/kc705_pcie.srcs/sources_1/ip/kc705_pcie_x8_gen2/synth/kc705_pcie_x8_gen2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_pcie_x8_gen2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/kc705_pcie/kc705_pcie.srcs/sources_1/ip/kc705_pcie_x8_gen2/kc705_pcie_x8_gen2.xci
# IP: The module: 'kc705_pcie_x8_gen2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/kc705_pcie/kc705_pcie.srcs/sources_1/ip/kc705_pcie_x8_gen2/source/kc705_pcie_x8_gen2-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_pcie_x8_gen2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/kc705_pcie/kc705_pcie.srcs/sources_1/ip/kc705_pcie_x8_gen2/synth/kc705_pcie_x8_gen2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_pcie_x8_gen2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
