# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7k325tffg900-2
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

read_ip c:/kc705_pcie/kc705_pcie.srcs/sources_1/ip/kc705_pcie_x8_gen2/kc705_pcie_x8_gen2.xci
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files c:/kc705_pcie/kc705_pcie.srcs/sources_1/ip/kc705_pcie_x8_gen2/kc705_pcie_x8_gen2.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/kc705_pcie/kc705_pcie.cache/wt [current_project]
set_property parent.project_dir C:/kc705_pcie [current_project]
catch { write_hwdef -file kc705_pcie_x8_gen2.hwdef }
synth_design -top kc705_pcie_x8_gen2 -part xc7k325tffg900-2 -mode out_of_context

rename_ref -prefix_all kc705_pcie_x8_gen2_
write_checkpoint -noxdef kc705_pcie_x8_gen2.dcp
report_utilization -file kc705_pcie_x8_gen2_utilization_synth.rpt -pb kc705_pcie_x8_gen2_utilization_synth.pb
if { [catch {
  file copy -force C:/kc705_pcie/kc705_pcie.runs/kc705_pcie_x8_gen2_synth_1/kc705_pcie_x8_gen2.dcp c:/kc705_pcie/kc705_pcie.srcs/sources_1/ip/kc705_pcie_x8_gen2/kc705_pcie_x8_gen2.dcp
  write_verilog -force -mode synth_stub c:/kc705_pcie/kc705_pcie.srcs/sources_1/ip/kc705_pcie_x8_gen2/kc705_pcie_x8_gen2_stub.v
  write_vhdl -force -mode synth_stub c:/kc705_pcie/kc705_pcie.srcs/sources_1/ip/kc705_pcie_x8_gen2/kc705_pcie_x8_gen2_stub.vhdl
  write_verilog -force -mode funcsim c:/kc705_pcie/kc705_pcie.srcs/sources_1/ip/kc705_pcie_x8_gen2/kc705_pcie_x8_gen2_funcsim.v
  write_vhdl -force -mode funcsim c:/kc705_pcie/kc705_pcie.srcs/sources_1/ip/kc705_pcie_x8_gen2/kc705_pcie_x8_gen2_funcsim.vhdl
} _RESULT ] } { 
  send_msg_id runtcl-3 error "Unable to successfully create or copy supporting IP files."
  return -code error
}
