function Hd = ddc_srrc
%DDC_SRRC Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.2 and the Signal Processing Toolbox 6.5.
%
% Generated on: 01-Mar-2007 18:07:47
%

% FIR Window Raised-cosine filter designed using the FIRRCOS function.

% All frequency values are in MHz.
Fs = 15.36;  % Sampling Frequency

N             = 94;         % Order
Fc            = 1.92;       % Cutoff Frequency
TM            = 'Rolloff';  % Transition Mode
R             = 0.22;       % Rolloff
DT            = 'sqrt';     % Design Type
SidelobeAtten = 50;         % Window Parameter

% Create the window vector for the design algorithm.
win = chebwin(N+1, SidelobeAtten);

% Calculate the coefficients using the FIRRCOS function.
b  = firrcos(N, Fc/(Fs/2), R, 2, TM, DT, [], win);
Hd = dfilt.dffir(b);

set(Hd, 'Arithmetic', 'double');


% [EOF]
