function Hd = SRRC
%SRRC Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.1 and the Signal Processing Toolbox 6.4.
%
% Generated on: 10-Jan-2007 19:02:02
%

% FIR Window Raised-cosine filter designed using the FIRRCOS function.

% All frequency values are in MHz.
Fs = 7.68;  % Sampling Frequency

N             = 44;         % Order
Fc            = 1.92;       % Cutoff Frequency
TM            = 'Rolloff';  % Transition Mode
R             = 0.22;       % Rolloff
DT            = 'sqrt';     % Design Type
SidelobeAtten = 27;         % Window Parameter

% Create the window vector for the design algorithm.
win = chebwin(N+1, SidelobeAtten);

% Calculate the coefficients using the FIRRCOS function.
b  = firrcos(N, Fc/(Fs/2), R, 2, TM, DT, [], win);
Hd = dfilt.dffir(b);


% [EOF]
