# Tcl script generated by PlanAhead

set tclUtilsPath "C:/Xilinx/13.4/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set cgProjectPath "C:/k7dsp_rtl_tutorial/RTL/Reference_Design/implementation/VHDL/PlanAhead/KC705_fmc150.srcs/sources_1/ip/fir_compiler_v6_3_0/coregen.cgc"

set ipName "duc_srrc"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

set bomFilePath "C:/k7dsp_rtl_tutorial/RTL/Reference_Design/implementation/VHDL/PlanAhead/KC705_fmc150.srcs/sources_1/ip/fir_compiler_v6_3_0/pa_cg_bom.xml"

set cgPartSpec "7k325t-2ffg900"

set hdlType "VHDL"

# generate the IP
set result [source "C:/Xilinx/13.4/ISE_DS/PlanAhead/scripts/pa_cg_reconfig_core.tcl"]

exit $result

