# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/example_design/example_ibert_bank_115_116.xdc

# IP: ip/ibert_bank_115_116/ibert_bank_115_116.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ibert_bank_115_116 || ORIG_REF_NAME==ibert_bank_115_116}]
