# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/example_design/xilinx_pcie_7x_ep_x8g2_KC705_REVC.xdc

# IP: ip/kc705_pcie_x8_gen2/kc705_pcie_x8_gen2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kc705_pcie_x8_gen2 || ORIG_REF_NAME==kc705_pcie_x8_gen2}]
