# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==kc705_pcie_x8_gen2 || ORIG_REF_NAME==kc705_pcie_x8_gen2}]]
