# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

read_ip C:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/ip/kc705_pcie_x8_gen2/kc705_pcie_x8_gen2.xci
set_property used_in_implementation false [get_files c:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/ip/kc705_pcie_x8_gen2/kc705_pcie_x8_gen2.dcp]
set_property used_in_implementation false [get_files -all c:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/ip/kc705_pcie_x8_gen2/kc705_pcie_x8_gen2.dcp]
set_property used_in_implementation false [get_files -all c:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/ip/kc705_pcie_x8_gen2/source/kc705_pcie_x8_gen2-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/ip/kc705_pcie_x8_gen2/synth/kc705_pcie_x8_gen2_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/ip/kc705_pcie_x8_gen2/kc705_pcie_x8_gen2.xci]

read_verilog -library xil_defaultlib {
  C:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/imports/kc705_pcie_x8_gen2/example_design/EP_MEM.v
  C:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/imports/kc705_pcie_x8_gen2/example_design/PIO_TX_ENGINE.v
  C:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/imports/kc705_pcie_x8_gen2/example_design/PIO_RX_ENGINE.v
  C:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/imports/kc705_pcie_x8_gen2/example_design/PIO_EP_MEM_ACCESS.v
  C:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/imports/kc705_pcie_x8_gen2/example_design/PIO_TO_CTRL.v
  C:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/imports/kc705_pcie_x8_gen2/example_design/PIO_EP.v
  C:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/imports/kc705_pcie_x8_gen2/example_design/support/kc705_pcie_x8_gen2_pipe_clock.v
  C:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/imports/kc705_pcie_x8_gen2/example_design/PIO.v
  C:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/imports/kc705_pcie_x8_gen2/example_design/support/kc705_pcie_x8_gen2_support.v
  C:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/imports/kc705_pcie_x8_gen2/example_design/pcie_app_7x.v
  C:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/sources_1/imports/kc705_pcie_x8_gen2/example_design/xilinx_pcie_2_1_ep_7x.v
}
read_xdc C:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/constrs_1/imports/example_design/xilinx_pcie_7x_ep_x8g2_KC705_REVC.xdc
set_property used_in_implementation false [get_files C:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.srcs/constrs_1/imports/example_design/xilinx_pcie_7x_ep_x8g2_KC705_REVC.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/kc705_pcie/kc705_pcie_x8_gen2_example/kc705_pcie_x8_gen2_example.cache/wt [current_project]
set_property parent.project_dir C:/kc705_pcie/kc705_pcie_x8_gen2_example [current_project]
catch { write_hwdef -file xilinx_pcie_2_1_ep_7x.hwdef }
synth_design -top xilinx_pcie_2_1_ep_7x -part xc7k325tffg900-2
write_checkpoint xilinx_pcie_2_1_ep_7x.dcp
report_utilization -file xilinx_pcie_2_1_ep_7x_utilization_synth.rpt -pb xilinx_pcie_2_1_ep_7x_utilization_synth.pb
