webtalk_init -webtalk_dir C:\\kc705_bist\\kc705_bist.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May 31 14:50:23 2014" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "2172_1244_1375396895_242" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "lesc3ue0q1fnvitsvufd8e80vg" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.2_34" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "34" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2680 0 @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2693 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "68.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1401569273183" -context "sdk\\\\bsp/1401569273183"
webtalk_add_data -client sdk -key hwid -value "1399617031311" -context "sdk\\\\bsp/1401569273183"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1401569273183"
webtalk_add_data -client sdk -key apptemplate -value "lwip_echo_server" -context "sdk\\\\bsp/1401569273183"
webtalk_add_data -client sdk -key uid -value "1401569274617" -context "sdk\\\\application/1401569274617"
webtalk_add_data -client sdk -key hwid -value "1399617031311" -context "sdk\\\\application/1401569274617"
webtalk_add_data -client sdk -key bspid -value "1401569273183" -context "sdk\\\\application/1401569274617"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1401569274617"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1401569274617"
webtalk_add_data -client sdk -key apptemplate -value "lwip_echo_server" -context "sdk\\\\application/1401569274617"
webtalk_transmit -clientid 916615809 -regid "2172_1244_1375396895_242" -xml C:\\kc705_bist\\kc705_bist.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\kc705_bist\\kc705_bist.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\kc705_bist\\kc705_bist.sdk\\webtalk\\sdk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
