# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/k7dsp_rtl_tut_sp_edit_v2/k7dsp_rtl_tut/RTL/RefDes/imp/VHDL/Vivado/Vivado.srcs/sources_1/ip/fir_compiler_v6_3_4/ddc_srrc.xci
# IP: The module: 'ddc_srrc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/k7dsp_rtl_tut_sp_edit_v2/k7dsp_rtl_tut/RTL/RefDes/imp/VHDL/Vivado/Vivado.srcs/sources_1/ip/fir_compiler_v6_3_4/ddc_srrc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddc_srrc'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/k7dsp_rtl_tut_sp_edit_v2/k7dsp_rtl_tut/RTL/RefDes/imp/VHDL/Vivado/Vivado.srcs/sources_1/ip/fir_compiler_v6_3_4/ddc_srrc.xci
# IP: The module: 'ddc_srrc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/k7dsp_rtl_tut_sp_edit_v2/k7dsp_rtl_tut/RTL/RefDes/imp/VHDL/Vivado/Vivado.srcs/sources_1/ip/fir_compiler_v6_3_4/ddc_srrc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddc_srrc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
