##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Thu May 8 06:45:59 2014
##  Generated by MIG Version 2.1
##  
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       KINTEX7
##                    FPGA Part:         XC7K325T-FFG900
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         800 MHz
##                    Time Period:       1250 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->SODIMMs->MT8JTF12864HZ-1G6
## Data Width: 64
## Time Period: 1250
## Data Mask: 1
##################################################################################################
          
# Set DCI_CASCADE          
set_property slave_banks {32 34} [get_iobanks 33]
############## NET - IOSTANDARD ##################
# Bank: 33 - GPIO_SW_S (CPU_RESET)
set_property VCCAUX_IO DONTCARE [get_ports {sys_rst}]
set_property SLEW FAST [get_ports {sys_rst}]
set_property IOSTANDARD LVCMOS15 [get_ports {sys_rst}]
set_property LOC AB12 [get_ports {sys_rst}]

# Bank: 33 - GPIO_LED_0_LS
set_property DRIVE 12 [get_ports {led[0]}]
set_property SLEW SLOW [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[0]}]
set_property LOC AB8 [get_ports {led[0]}]

# Bank: 33 - GPIO_LED_1_LS
set_property DRIVE 12 [get_ports {led[1]}]
set_property SLEW SLOW [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[1]}]
set_property LOC AA8 [get_ports {led[1]}]

# Bank: 33 - GPIO_LED_2_LS
set_property DRIVE 12 [get_ports {led[2]}]
set_property SLEW SLOW [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[2]}]
set_property LOC AC9 [get_ports {led[2]}]

# Bank: 33 - GPIO_LED_3_LS
set_property DRIVE 12 [get_ports {led[3]}]
set_property SLEW SLOW [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[3]}]
set_property LOC AB9 [get_ports {led[3]}]

