# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/k7dsp_rtl_tut_sp_edit_v2/k7dsp_rtl_tut/RTL/RefDes/imp/VHDL/Vivado/Vivado.srcs/sources_1/ip/dds_compiler_v5_0_2/DDS.xci
# IP: The module: 'DDS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/k7dsp_rtl_tut_sp_edit_v2/k7dsp_rtl_tut/RTL/RefDes/imp/VHDL/Vivado/Vivado.srcs/sources_1/ip/dds_compiler_v5_0_2/DDS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDS'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/k7dsp_rtl_tut_sp_edit_v2/k7dsp_rtl_tut/RTL/RefDes/imp/VHDL/Vivado/Vivado.srcs/sources_1/ip/dds_compiler_v5_0_2/DDS.xci
# IP: The module: 'DDS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/k7dsp_rtl_tut_sp_edit_v2/k7dsp_rtl_tut/RTL/RefDes/imp/VHDL/Vivado/Vivado.srcs/sources_1/ip/dds_compiler_v5_0_2/DDS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDS'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
