xdma/xdma_user.c File Reference
xdma_user.c File Reference
#include <linux/kernel.h>
#include <linux/timer.h>
#include <linux/jiffies.h>
#include <linux/pci.h>
#include "xbasic_types.h"
#include "xdebug.h"
#include "xstatus.h"
#include "xio.h"
#include "xdma.h"
#include "xdma_bd.h"
#include "xdma_user.h"
#include "xdma_hw.h"
Functions
void * DmaRegister (int engine, int bar, UserPtrs *uptr, int pktsize)
int DmaUnregister (void *handle)
void DmaFifoEmptyWait (int handleId, u32 type)
int DmaSendPkt (void *handle, PktBuf *pkts, int numpkts)
Detailed Description
Contains the APIs used by the application-specific drivers.
Author: Xilinx, Inc.
2007-2010 (c) Xilinx, Inc. This file is licensed uner the terms of the GNU General Public License version 2.1. This program is licensed "as is" without any warranty of any kind, whether express or implied.
 MODIFICATION HISTORY:
 Ver   Date     Changes
 ----- -------- -------------------------------------------------------
 1.0   12/07/09 First release
Function Documentation
void* DmaRegister (int engine, int bar, UserPtrs * uptr, int pktsize)
This function must be called by the user driver to register itself with the base DMA driver. After doing required checks to verify the choice of engine and BAR register, it initializes the engine and the BD ring associated with the engine, and enables interrupts if required.
Only one user is supported per engine at any given time. Incase the engine has already been registered with another user driver, an error will be returned.
Parameters:
engine is the DMA engine the user driver wants to use.
bar is the BAR register the user driver wants to use.
uptr is a pointer to the function callbacks in the user driver.
pktsize is the size of packets that the user driver will normally use.
Returns:
NULL incase of any error in completing the registration.
Handle with which the user driver is registered.
Note:
This function should not be called in an interrupt context
References descriptor_init(), Dma_BdRingStart(), dmaData, INITIALIZED, UserPtrs::privData, USER_ASSIGNED, and UserPtrs::UserInit.
int DmaSendPkt (void * handle, PktBuf * pkts, int numpkts)
This function must be called by the user driver to unregister itself from the base DMA driver. After doing required checks to verify the handle and engine state, the DMA engine is reset, interrupts are disabled if required, and the BD ring is freed, while returning all the packet buffers to the user driver.
Parameters:
handle is the handle which was assigned during the registration process.
pkts is a PktBuf array, with the array of packets to be sent.
numpkts is the number of packets in the PktBuf array.
Returns:
0 incase of any error
Number of packets successfully queued for DMA send, incase of success.
Note:
There may not be enough BDs to accomodate the number of packets requested by the user driver, so the returned value may not match with the requested numpkts. The user driver must be written to manage this appropriately.
References PktBuf::bufInfo, Dma_BdRingAlloc(), Dma_BdRingToHw(), Dma_BdRingUnAlloc(), PktBuf::flags, INITIALIZED, PKT_ALL, PktBuf::pktBuf, PktBuf::size, USER_ASSIGNED, and PktBuf::userInfo.
int DmaUnregister (void * handle)
This function must be called by the user driver to unregister itself from the base DMA driver. After doing required checks to verify the handle and engine state, the DMA engine is reset, interrupts are disabled if required, and the BD ring is freed, while returning all the packet buffers to the user driver.
Parameters:
handle is the handle which was assigned during the registration process.
Returns:
XST_FAILURE incase of any error
0 incase of success
Note:
This function should not be called in an interrupt context
References descriptor_free(), Dma_Reset(), dmaData, INITIALIZED, UNREGISTERING, and USER_ASSIGNED.