
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxiethernet.h"

/*
* The configuration table for devices
*/

XAxiEthernet_Config XAxiEthernet_ConfigTable[] =
{
	{
		XPAR_AXIETHERNET_0_DEVICE_ID,
		XPAR_AXIETHERNET_0_BASEADDR,
		XPAR_AXIETHERNET_0_TEMAC_TYPE,
		XPAR_AXIETHERNET_0_TXCSUM,
		XPAR_AXIETHERNET_0_RXCSUM,
		XPAR_AXIETHERNET_0_PHY_TYPE,
		XPAR_AXIETHERNET_0_TXVLAN_TRAN,
		XPAR_AXIETHERNET_0_RXVLAN_TRAN,
		XPAR_AXIETHERNET_0_TXVLAN_TAG,
		XPAR_AXIETHERNET_0_RXVLAN_TAG,
		XPAR_AXIETHERNET_0_TXVLAN_STRP,
		XPAR_AXIETHERNET_0_RXVLAN_STRP,
		XPAR_AXIETHERNET_0_MCAST_EXTEND,
		XPAR_AXIETHERNET_0_STATS,
		XPAR_AXIETHERNET_0_AVB,
		XPAR_AXIETHERNET_0_ENABLE_SGMII_OVER_LVDS,
		XPAR_AXIETHERNET_0_INTR,
		XPAR_AXIETHERNET_0_CONNECTED_TYPE,
		XPAR_AXIETHERNET_0_CONNECTED_BASEADDR,
		0xFF,
		XPAR_AXIETHERNET_0_CONNECTED_DMARX_INTR,
		XPAR_AXIETHERNET_0_CONNECTED_DMATX_INTR
	}
};

