
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xhwicap.h"

/*
* The configuration table for devices
*/

XHwIcap_Config XHwIcap_ConfigTable[] =
{
	{
		XPAR_AXI_HWICAP_0_DEVICE_ID,
		XPAR_AXI_HWICAP_0_BASEADDR,
		XPAR_AXI_HWICAP_0_ICAP_DWIDTH,
		XPAR_AXI_HWICAP_0_MODE
	}
};


