# Tcl script generated by PlanAhead

set tclUtilsPath "C:/Xilinx/13.4/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set cgProjectPath "C:/kintex7dsp_getting_started_reference_design/RTL/Reference_Design/implementation/VHDL/PlanAhead/K7RTLTut/K7RTLTut.srcs/sources_1/ip/fir_compiler_v6_3_0/coregen.cgc"

set ipFile "C:/kintex7dsp_getting_started_reference_design/RTL/Reference_Design/implementation/VHDL/PlanAhead/K7RTLTut/K7RTLTut.srcs/sources_1/ip/fir_compiler_v6_3_0/duc_srrc.xco"

set ipName "duc_srrc"

set chains "APPLY_CURRENT_PROJECT_OPTIONS_CHAIN BATCH_CUSTOMIZE_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

set vlnv "xilinx.com:ip:fir_compiler:6.3"

set cgPartSpec "7k325t-2ffg900"

set bomFilePath "C:/kintex7dsp_getting_started_reference_design/RTL/Reference_Design/implementation/VHDL/PlanAhead/K7RTLTut/K7RTLTut.srcs/sources_1/ip/fir_compiler_v6_3_0/pa_cg_bom.xml"

set hdlType "VHDL"

# migrate the project
set result [source "C:/Xilinx/13.4/ISE_DS/PlanAhead/scripts/pa_cg_migrate_project.tcl"]

exit $result

