# Tcl script generated by PlanAhead

set tclUtilsPath "C:/Xilinx/13.4/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set cgProjectPath "C:/kintex7dsp_getting_started_reference_design/RTL/Reference_Design/implementation/VHDL/PlanAhead/K7RTLTut/K7RTLTut.srcs/sources_1/ip/fir_compiler_v6_3_0/coregen.cgc"

set ipName "duc_srrc"

set hdlType "VHDL"

set cgPartSpec "7k325t-2ffg900"

set chains "GENERATE_CURRENT_CHAIN"

set bomFilePath "C:/kintex7dsp_getting_started_reference_design/RTL/Reference_Design/implementation/VHDL/PlanAhead/K7RTLTut/K7RTLTut.srcs/sources_1/ip/fir_compiler_v6_3_0/pa_cg_bom.xml"

# generate the IP
set result [source "C:/Xilinx/13.4/ISE_DS/PlanAhead/scripts/pa_cg_gen_core.tcl"]

exit $result

