function Hd = halfband2
%HALFBAND2 Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.1 and the Signal Processing Toolbox 6.4.
%
% Generated on: 10-Jan-2007 18:49:47
%

% Equiripple Halfband lowpass filter designed using the FIRPM function.

% All frequency values are normalized to 1.

Fpass = 0.1525;            % Passband Frequency
Dpass = 0.00011512925414;  % Passband Ripple

% Calculate the coefficients using the FIRPM function.
b  = firhalfband('minorder', Fpass, Dpass);
Hd = dfilt.dffir(b);


% [EOF]
