set_property SRC_FILE_INFO {cfile:c:/k7dsp_rtl_tut_sp_edit_v2/k7dsp_rtl_tut/RTL/RefDes/imp/VHDL/Vivado/Vivado.srcs/sources_1/ip/mmcm/mmcm.xdc rfile:../../../Vivado.srcs/sources_1/ip/mmcm/mmcm.xdc id:1 order:EARLY scoped_inst:mmcm_inst/U0} [current_design]
set_property SRC_FILE_INFO {cfile:C:/k7dsp_rtl_tut_sp_edit_v2/k7dsp_rtl_tut/RTL/RefDes/imp/VHDL/Vivado/Vivado.srcs/constrs_1/imports/k7_TRD/k7dsp_rtl_tutorial.xdc rfile:../../../Vivado.srcs/constrs_1/imports/k7_TRD/k7dsp_rtl_tutorial.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports CLK_IN1]] 0.050000000000000003
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of [get_pins mmcm_adac_inst/U0/mmcm_adv_inst/CLKIN1]] 0.041
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of [get_pins mmcm_inst/U0/mmcm_adv_inst/CLKIN1]] 0.050
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y10 [get_cells {adc_data_a[4].ISERDESE2_adc_cha}]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y10 [get_cells {adc_data_a[4].IDELAYE2_inst_ADC_ch_A}]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y12 [get_cells {adc_data_a[1].ISERDESE2_adc_cha}]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y12 [get_cells {adc_data_a[1].IDELAYE2_inst_ADC_ch_A}]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y14 [get_cells {adc_data_a[6].ISERDESE2_adc_cha}]
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y14 [get_cells {adc_data_a[6].IDELAYE2_inst_ADC_ch_A}]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y16 [get_cells {adc_data_b[1].ISERDESE2_adc_chb}]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y16 [get_cells {adc_data_b[1].IDELAYE2_inst_ADC_ch_B}]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y18 [get_cells {adc_data_b[3].ISERDESE2_adc_chb}]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y18 [get_cells {adc_data_b[3].IDELAYE2_inst_ADC_ch_B}]
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y2 [get_cells {adc_data_a[5].ISERDESE2_adc_cha}]
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y2 [get_cells {adc_data_a[5].IDELAYE2_inst_ADC_ch_A}]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y20 [get_cells {adc_data_b[2].ISERDESE2_adc_chb}]
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y20 [get_cells {adc_data_b[2].IDELAYE2_inst_ADC_ch_B}]
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y26 [get_cells IDELAYE2_inst_ADC_CLK]
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y28 [get_cells {adc_data_a[0].ISERDESE2_adc_cha}]
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y28 [get_cells {adc_data_a[0].IDELAYE2_inst_ADC_ch_A}]
set_property src_info {type:XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y30 [get_cells {adc_data_b[6].ISERDESE2_adc_chb}]
set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y30 [get_cells {adc_data_b[6].IDELAYE2_inst_ADC_ch_B}]
set_property src_info {type:XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y36 [get_cells {adc_data_b[5].ISERDESE2_adc_chb}]
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y36 [get_cells {adc_data_b[5].IDELAYE2_inst_ADC_ch_B}]
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y38 [get_cells {adc_data_b[4].ISERDESE2_adc_chb}]
set_property src_info {type:XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y38 [get_cells {adc_data_b[4].IDELAYE2_inst_ADC_ch_B}]
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y4 [get_cells {adc_data_a[3].ISERDESE2_adc_cha}]
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y4 [get_cells {adc_data_a[3].IDELAYE2_inst_ADC_ch_A}]
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y6 [get_cells {adc_data_a[2].ISERDESE2_adc_cha}]
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y6 [get_cells {adc_data_a[2].IDELAYE2_inst_ADC_ch_A}]
set_property src_info {type:XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y8 [get_cells {adc_data_b[0].ISERDESE2_adc_chb}]
set_property src_info {type:XDC file:2 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y8 [get_cells {adc_data_b[0].IDELAYE2_inst_ADC_ch_B}]
set_property src_info {type:XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y70 [get_cells {dac_data[0].oserdes_data}]
set_property src_info {type:XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y62 [get_cells {dac_data[1].oserdes_data}]
set_property src_info {type:XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y64 [get_cells {dac_data[2].oserdes_data}]
set_property src_info {type:XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y56 [get_cells {dac_data[3].oserdes_data}]
set_property src_info {type:XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y54 [get_cells {dac_data[4].oserdes_data}]
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y52 [get_cells {dac_data[5].oserdes_data}]
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y78 [get_cells {dac_data[6].oserdes_data}]
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y76 [get_cells {dac_data[7].oserdes_data}]
set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y58 [get_cells oserdes_clock]
set_property src_info {type:XDC file:2 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y60 [get_cells oserdes_frame]
set_property src_info {type:XDC file:2 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
