# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Sam/Vivado Projects/ethernet_mig_sp/ethernet_mig_sp.srcs/sources_1/ip/axi_interconnect_0/axi_interconnect_0.xci
# IP: The module: 'axi_interconnect_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Sam/Vivado Projects/ethernet_mig_sp/ethernet_mig_sp.srcs/sources_1/ip/axi_interconnect_0/axi_interconnect_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Sam/Vivado Projects/ethernet_mig_sp/ethernet_mig_sp.srcs/sources_1/ip/axi_interconnect_0/axi_interconnect_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Sam/Vivado Projects/ethernet_mig_sp/ethernet_mig_sp.srcs/sources_1/ip/axi_interconnect_0/axi_interconnect_0_impl_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/Sam/Vivado Projects/ethernet_mig_sp/ethernet_mig_sp.srcs/sources_1/ip/axi_interconnect_0/axi_interconnect_0.xci
# IP: The module: 'axi_interconnect_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Sam/Vivado Projects/ethernet_mig_sp/ethernet_mig_sp.srcs/sources_1/ip/axi_interconnect_0/axi_interconnect_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Sam/Vivado Projects/ethernet_mig_sp/ethernet_mig_sp.srcs/sources_1/ip/axi_interconnect_0/axi_interconnect_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Sam/Vivado Projects/ethernet_mig_sp/ethernet_mig_sp.srcs/sources_1/ip/axi_interconnect_0/axi_interconnect_0_impl_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
