# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/k7_TRD/k7dsp_rtl_tutorial.xdc

# IP: ip/vio/vio.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio || ORIG_REF_NAME==vio}]

# IP: ip/mmcm_adac/mmcm_adac.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mmcm_adac || ORIG_REF_NAME==mmcm_adac}]

# IP: ip/mmcm/mmcm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mmcm || ORIG_REF_NAME==mmcm}]

# IP: ip/ila/ila.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila || ORIG_REF_NAME==ila}]

# XDC: ip/vio/vio_ooc.xdc

# XDC: ip/vio/vio.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vio || ORIG_REF_NAME==vio}] {/inst }]/inst ]]

# XDC: ip/mmcm_adac/mmcm_adac.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmcm_adac || ORIG_REF_NAME==mmcm_adac}] {/U0 }]/U0 ]]

# XDC: ip/mmcm_adac/mmcm_adac_ooc.xdc

# XDC: ip/mmcm_adac/mmcm_adac_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmcm_adac || ORIG_REF_NAME==mmcm_adac}] {/U0 }]/U0 ]]

# XDC: ip/mmcm/mmcm.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmcm || ORIG_REF_NAME==mmcm}] {/U0 }]/U0 ]]

# XDC: ip/mmcm/mmcm_ooc.xdc

# XDC: ip/mmcm/mmcm_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmcm || ORIG_REF_NAME==mmcm}] {/U0 }]/U0 ]]

# XDC: ip/ila/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila || ORIG_REF_NAME==ila}]

# XDC: ip/ila/ila_ooc.xdc
