# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/k7dsp_rtl_tut_sp_edit_v2/RTL/RefDes/imp/VHDL/Vivado/Vivado.srcs/sources_1/ip/SP_DDS/SP_DDS.xci
# IP: The module: 'SP_DDS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/k7dsp_rtl_tut_sp_edit_v2/RTL/RefDes/imp/VHDL/Vivado/Vivado.srcs/sources_1/ip/SP_DDS/SP_DDS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SP_DDS'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/k7dsp_rtl_tut_sp_edit_v2/RTL/RefDes/imp/VHDL/Vivado/Vivado.srcs/sources_1/ip/SP_DDS/SP_DDS.xci
# IP: The module: 'SP_DDS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/k7dsp_rtl_tut_sp_edit_v2/RTL/RefDes/imp/VHDL/Vivado/Vivado.srcs/sources_1/ip/SP_DDS/SP_DDS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SP_DDS'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
