# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/kc705_multiboot/system.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_axi_bram_ctrl_0_0/system_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_0_0 || ORIG_REF_NAME==system_axi_bram_ctrl_0_0}]

# IP: bd/system/ip/system_axi_bram_ctrl_0_bram_0/system_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==system_axi_bram_ctrl_0_bram_0}]

# IP: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0}]

# IP: bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_2_0 || ORIG_REF_NAME==system_axi_gpio_2_0}]

# IP: bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_3_0 || ORIG_REF_NAME==system_axi_gpio_3_0}]

# IP: bd/system/ip/system_axi_hwicap_0_0/system_axi_hwicap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hwicap_0_0 || ORIG_REF_NAME==system_axi_hwicap_0_0}]

# IP: bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_quad_spi_0_0 || ORIG_REF_NAME==system_axi_quad_spi_0_0}]

# IP: bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_timer_0_0 || ORIG_REF_NAME==system_axi_timer_0_0}]

# IP: bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uart16550_0_0 || ORIG_REF_NAME==system_axi_uart16550_0_0}]

# IP: bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_1_0 || ORIG_REF_NAME==system_clk_wiz_1_0}]

# IP: bd/system/ip/system_mdm_1_0/system_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mdm_1_0 || ORIG_REF_NAME==system_mdm_1_0}]

# IP: bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_0 || ORIG_REF_NAME==system_microblaze_0_0}]

# IP: bd/system/ip/system_microblaze_0_axi_intc_0/system_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_intc_0 || ORIG_REF_NAME==system_microblaze_0_axi_intc_0}]

# IP: bd/system/ip/system_microblaze_0_axi_periph_0/system_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_periph_0 || ORIG_REF_NAME==system_microblaze_0_axi_periph_0}]

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0}]

# IP: bd/system/ip/system_dlmb_bram_if_cntlr_0/system_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==system_dlmb_bram_if_cntlr_0}]

# IP: bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_v10_0 || ORIG_REF_NAME==system_dlmb_v10_0}]

# IP: bd/system/ip/system_ilmb_bram_if_cntlr_0/system_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==system_ilmb_bram_if_cntlr_0}]

# IP: bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_v10_0 || ORIG_REF_NAME==system_ilmb_v10_0}]

# IP: bd/system/ip/system_lmb_bram_0/system_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_0 || ORIG_REF_NAME==system_lmb_bram_0}]

# IP: bd/system/ip/system_microblaze_0_xlconcat_0/system_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_xlconcat_0 || ORIG_REF_NAME==system_microblaze_0_xlconcat_0}]

# IP: bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_1_0 || ORIG_REF_NAME==system_proc_sys_reset_1_0}]

# IP: bd/system/ip/system_xlconstant_1_0/system_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_1_0 || ORIG_REF_NAME==system_xlconstant_1_0}]

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0}]

# XDC: bd/system/ip/system_axi_bram_ctrl_0_0/system_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_bram_ctrl_0_bram_0/system_axi_bram_ctrl_0_bram_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_2_0 || ORIG_REF_NAME==system_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_2_0 || ORIG_REF_NAME==system_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_3_0 || ORIG_REF_NAME==system_axi_gpio_3_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_3_0 || ORIG_REF_NAME==system_axi_gpio_3_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_hwicap_0_0/system_axi_hwicap_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hwicap_0_0 || ORIG_REF_NAME==system_axi_hwicap_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_hwicap_0_0/system_axi_hwicap_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hwicap_0_0 || ORIG_REF_NAME==system_axi_hwicap_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_hwicap_0_0/system_axi_hwicap_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_quad_spi_0_0 || ORIG_REF_NAME==system_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_quad_spi_0_0 || ORIG_REF_NAME==system_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_quad_spi_0_0 || ORIG_REF_NAME==system_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_timer_0_0 || ORIG_REF_NAME==system_axi_timer_0_0}]

# XDC: bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uart16550_0_0 || ORIG_REF_NAME==system_axi_uart16550_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uart16550_0_0 || ORIG_REF_NAME==system_axi_uart16550_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_1_0 || ORIG_REF_NAME==system_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0_ooc.xdc

# XDC: bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_1_0 || ORIG_REF_NAME==system_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_mdm_1_0/system_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mdm_1_0 || ORIG_REF_NAME==system_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mdm_1_0/system_mdm_1_0_ooc.xdc

# XDC: bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_microblaze_0_0 || ORIG_REF_NAME==system_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_microblaze_0_0/system_microblaze_0_0_ooc.xdc

# XDC: bd/system/ip/system_microblaze_0_axi_intc_0/system_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_intc_0 || ORIG_REF_NAME==system_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_microblaze_0_axi_intc_0/system_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_intc_0 || ORIG_REF_NAME==system_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_microblaze_0_axi_intc_0/system_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_dlmb_bram_if_cntlr_0/system_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_dlmb_v10_0 || ORIG_REF_NAME==system_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0_ooc.xdc

# XDC: bd/system/ip/system_ilmb_bram_if_cntlr_0/system_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ilmb_v10_0 || ORIG_REF_NAME==system_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0_ooc.xdc

# XDC: bd/system/ip/system_lmb_bram_0/system_lmb_bram_0_ooc.xdc

# XDC: bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_1_0 || ORIG_REF_NAME==system_proc_sys_reset_1_0}]

# XDC: bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0_ooc.xdc

# XDC: bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_1_0 || ORIG_REF_NAME==system_proc_sys_reset_1_0}]

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
