# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

add_files C:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_0/system_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_bram_0/system_axi_bram_ctrl_0_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_hwicap_0_0/system_axi_hwicap_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_hwicap_0_0/system_axi_hwicap_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_hwicap_0_0/system_axi_hwicap_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_axi_uart16550_0_0/system_axi_uart16550_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_mdm_1_0/system_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_mdm_1_0/system_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_microblaze_0_axi_intc_0/system_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_microblaze_0_axi_intc_0/system_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_microblaze_0_axi_intc_0/system_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_dlmb_bram_if_cntlr_0/system_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_ilmb_bram_if_cntlr_0/system_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_lmb_bram_0/system_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/system_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib C:/kc705_multiboot/kc705_multiboot.srcs/sources_1/bd/system/hdl/system_wrapper.v
read_xdc C:/kc705_multiboot/kc705_multiboot.srcs/constrs_1/imports/kc705_multiboot/system.xdc
set_property used_in_implementation false [get_files C:/kc705_multiboot/kc705_multiboot.srcs/constrs_1/imports/kc705_multiboot/system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/kc705_multiboot/kc705_multiboot.cache/wt [current_project]
set_property parent.project_dir C:/kc705_multiboot [current_project]
catch { write_hwdef -file system_wrapper.hwdef }
synth_design -top system_wrapper -part xc7k325tffg900-2
write_checkpoint system_wrapper.dcp
report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb
