# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/example_design/kc705_ethernet_rgmii_example_design.xdc

# XDC: imports/example_design/kc705_ethernet_rgmii_user_phytiming.xdc

# IP: ip/kc705_ethernet_rgmii/kc705_ethernet_rgmii.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kc705_ethernet_rgmii || ORIG_REF_NAME==kc705_ethernet_rgmii}]
