# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

read_ip C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/ip/kc705_ethernet_rgmii/kc705_ethernet_rgmii.xci
set_property used_in_implementation false [get_files c:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/ip/kc705_ethernet_rgmii/kc705_ethernet_rgmii.dcp]
set_property used_in_implementation false [get_files -all c:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/ip/kc705_ethernet_rgmii/kc705_ethernet_rgmii.dcp]
set_property used_in_implementation false [get_files -all c:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/ip/kc705_ethernet_rgmii/synth/kc705_ethernet_rgmii.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/ip/kc705_ethernet_rgmii/synth/kc705_ethernet_rgmii_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/ip/kc705_ethernet_rgmii/synth/kc705_ethernet_rgmii_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/ip/kc705_ethernet_rgmii/synth/kc705_ethernet_rgmii_board.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/ip/kc705_ethernet_rgmii/kc705_ethernet_rgmii.xci]

read_verilog -library xil_defaultlib {
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/fifo/kc705_ethernet_rgmii_bram_tdp.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/common/kc705_ethernet_rgmii_sync_block.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/common/kc705_ethernet_rgmii_reset_sync.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/support/kc705_ethernet_rgmii_support_resets.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/support/kc705_ethernet_rgmii_support_clocking.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/fifo/kc705_ethernet_rgmii_tx_client_fifo.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/fifo/kc705_ethernet_rgmii_rx_client_fifo.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/support/kc705_ethernet_rgmii_support.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/pat_gen/kc705_ethernet_rgmii_axi_pipe.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/pat_gen/kc705_ethernet_rgmii_axi_pat_gen.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/pat_gen/kc705_ethernet_rgmii_axi_pat_check.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/pat_gen/kc705_ethernet_rgmii_axi_mux.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/pat_gen/kc705_ethernet_rgmii_address_swap.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/kc705_ethernet_rgmii_clk_wiz.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/fifo/kc705_ethernet_rgmii_ten_100_1g_eth_fifo.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/pat_gen/kc705_ethernet_rgmii_basic_pat_gen.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/kc705_ethernet_rgmii_fifo_block.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/kc705_ethernet_rgmii_example_design_resets.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/kc705_ethernet_rgmii_example_design_clocks.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/axi_lite_sm/kc705_ethernet_rgmii_axi_lite_sm.v
  C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/sources_1/imports/example_design/kc705_ethernet_rgmii_example_design.v
}
read_xdc C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/constrs_1/imports/example_design/kc705_ethernet_rgmii_example_design.xdc
set_property used_in_implementation false [get_files C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/constrs_1/imports/example_design/kc705_ethernet_rgmii_example_design.xdc]

read_xdc C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/constrs_1/imports/example_design/kc705_ethernet_rgmii_user_phytiming.xdc
set_property used_in_implementation false [get_files C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/constrs_1/imports/example_design/kc705_ethernet_rgmii_user_phytiming.xdc]
set_property processing_order LATE [get_files C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.srcs/constrs_1/imports/example_design/kc705_ethernet_rgmii_user_phytiming.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/kc705_ethernet/kc705_ethernet_rgmii_example/kc705_ethernet_rgmii_example.cache/wt [current_project]
set_property parent.project_dir C:/kc705_ethernet/kc705_ethernet_rgmii_example [current_project]
catch { write_hwdef -file kc705_ethernet_rgmii_example_design.hwdef }
synth_design -top kc705_ethernet_rgmii_example_design -part xc7k325tffg900-2
write_checkpoint kc705_ethernet_rgmii_example_design.dcp
report_utilization -file kc705_ethernet_rgmii_example_design_utilization_synth.rpt -pb kc705_ethernet_rgmii_example_design_utilization_synth.pb
